#!/bin/bash

: '
    ** Copyright (c) 2017, Autonomous Networks Research Group. All rights reserved.
    **     contributor: Quynh Nguyen, Bhaskar Krishnamachari
    **     Read license file in main directory for more details
'

source_file=$1
account=$2
remote_file=$3
remote_password=$4
sshpass -p $remote_password scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q $source_file $account:~/$remote_file