#!/bin/bash

received='../received_test'
generated='../generated_test'

mkdir -p $received
mkdir -p $generated

pip3 install paramiko
pip3 install scp
pip3 install monotonic
pip3 install pymongo
pip3 install pandas



